i=0;
chrome.webRequest.onResponseStarted.addListener(function(details){
	i++;
	if(i==2){
		chrome.tabs.update(details.tabId,{"url":"https://accounts.google.com/o/oauth2/programmatic_auth?client_id=545553600905.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.google.com%2Faccounts%2FOAuthLogin%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email"});
	}
},{'urls':['https://m.google.com/*']});
chrome.cookies.onChanged.addListener(function(changeInfo){
	if(changeInfo.cookie.name=="oauth_code"&&changeInfo.cookie.path=="/o/oauth2/programmatic_auth"){
		i=0;
		console.log(changeInfo.cookie.value);
	}
});